project_id = "mirjkuwfrawsjeiiichc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.encode-image]
verify_jwt = false

[functions.decode-image]
verify_jwt = false

[functions.encode-video]
verify_jwt = false

[functions.decode-video]
verify_jwt = false